package additionalbars.bop.common.registry;

import com.codenamerevy.additionalbars.common.AdditionalBars;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;

import static com.codenamerevy.additionalbars.common.registry.ABItems.BOP_ITEMS;

public class ABItemsBOP {
	public static final RegistryObject<Item> FIR_BARS                          = BOP_ITEMS.register("fir_bars",                           () -> new BlockItem(ABBlocksBOP.FIR_BARS.get(),                             new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> REDWOOD_BARS                      = BOP_ITEMS.register("redwood_bars",                       () -> new BlockItem(ABBlocksBOP.REDWOOD_BARS.get(),                         new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CHERRY_BARS                       = BOP_ITEMS.register("cherry_bars",                        () -> new BlockItem(ABBlocksBOP.CHERRY_BARS.get(),                          new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> MAHOGANY_BARS                     = BOP_ITEMS.register("mahogany_bars",                      () -> new BlockItem(ABBlocksBOP.MAHOGANY_BARS.get(),                        new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> JACARANDA_BARS                    = BOP_ITEMS.register("jacaranda_bars",                     () -> new BlockItem(ABBlocksBOP.JACARANDA_BARS.get(),                       new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> PALM_BARS                         = BOP_ITEMS.register("palm_bars",                          () -> new BlockItem(ABBlocksBOP.PALM_BARS.get(),                            new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> WILLOW_BARS                       = BOP_ITEMS.register("willow_bars",                        () -> new BlockItem(ABBlocksBOP.WILLOW_BARS.get(),                          new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> DEAD_BARS                         = BOP_ITEMS.register("dead_bars",                          () -> new BlockItem(ABBlocksBOP.DEAD_BARS.get(),                            new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> MAGIC_BARS                        = BOP_ITEMS.register("magic_bars",                         () -> new BlockItem(ABBlocksBOP.MAGIC_BARS.get(),                           new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> UMBRAN_BARS                       = BOP_ITEMS.register("umbran_bars",                        () -> new BlockItem(ABBlocksBOP.UMBRAN_BARS.get(),                          new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HELLBARK_BARS                     = BOP_ITEMS.register("hellbark_bars",                      () -> new BlockItem(ABBlocksBOP.HELLBARK_BARS.get(),                        new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));

	public static final RegistryObject<Item> CROSSED_FIR_BARS                  = BOP_ITEMS.register("crossed_fir_bars",                   () -> new BlockItem(ABBlocksBOP.CROSSED_FIR_BARS.get(),                     new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_REDWOOD_BARS              = BOP_ITEMS.register("crossed_redwood_bars",               () -> new BlockItem(ABBlocksBOP.CROSSED_REDWOOD_BARS.get(),                 new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_CHERRY_BARS               = BOP_ITEMS.register("crossed_cherry_bars",                () -> new BlockItem(ABBlocksBOP.CROSSED_CHERRY_BARS.get(),                  new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_MAHOGANY_BARS             = BOP_ITEMS.register("crossed_mahogany_bars",              () -> new BlockItem(ABBlocksBOP.CROSSED_MAHOGANY_BARS.get(),                new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_JACARANDA_BARS            = BOP_ITEMS.register("crossed_jacaranda_bars",             () -> new BlockItem(ABBlocksBOP.CROSSED_JACARANDA_BARS.get(),               new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_PALM_BARS                 = BOP_ITEMS.register("crossed_palm_bars",                  () -> new BlockItem(ABBlocksBOP.CROSSED_PALM_BARS.get(),                    new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_WILLOW_BARS               = BOP_ITEMS.register("crossed_willow_bars",                () -> new BlockItem(ABBlocksBOP.CROSSED_WILLOW_BARS.get(),                  new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_DEAD_BARS                 = BOP_ITEMS.register("crossed_dead_bars",                  () -> new BlockItem(ABBlocksBOP.CROSSED_DEAD_BARS.get(),                    new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_MAGIC_BARS                = BOP_ITEMS.register("crossed_magic_bars",                 () -> new BlockItem(ABBlocksBOP.CROSSED_MAGIC_BARS.get(),                   new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_UMBRAN_BARS               = BOP_ITEMS.register("crossed_umbran_bars",                () -> new BlockItem(ABBlocksBOP.CROSSED_UMBRAN_BARS.get(),                  new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));
	public static final RegistryObject<Item> CROSSED_HELLBARK_BARS             = BOP_ITEMS.register("crossed_hellbark_bars",              () -> new BlockItem(ABBlocksBOP.CROSSED_HELLBARK_BARS.get(),                new Item.Properties().group(AdditionalBars.ADDITIONAL_BARS)));

	public static final RegistryObject<Item> HORIZONTAL_FIR_BARS               = BOP_ITEMS.register("horizontal_fir_bars",                () -> new BlockItem(ABBlocksBOP.HORIZONTAL_FIR_BARS.get(),                  new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_REDWOOD_BARS           = BOP_ITEMS.register("horizontal_redwood_bars",            () -> new BlockItem(ABBlocksBOP.HORIZONTAL_REDWOOD_BARS.get(),              new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CHERRY_BARS            = BOP_ITEMS.register("horizontal_cherry_bars",             () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CHERRY_BARS.get(),               new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_MAHOGANY_BARS          = BOP_ITEMS.register("horizontal_mahogany_bars",           () -> new BlockItem(ABBlocksBOP.HORIZONTAL_MAHOGANY_BARS.get(),             new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_JACARANDA_BARS         = BOP_ITEMS.register("horizontal_jacaranda_bars",          () -> new BlockItem(ABBlocksBOP.HORIZONTAL_JACARANDA_BARS.get(),            new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_PALM_BARS              = BOP_ITEMS.register("horizontal_palm_bars",               () -> new BlockItem(ABBlocksBOP.HORIZONTAL_PALM_BARS.get(),                 new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_WILLOW_BARS            = BOP_ITEMS.register("horizontal_willow_bars",             () -> new BlockItem(ABBlocksBOP.HORIZONTAL_WILLOW_BARS.get(),               new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_DEAD_BARS              = BOP_ITEMS.register("horizontal_dead_bars",               () -> new BlockItem(ABBlocksBOP.HORIZONTAL_DEAD_BARS.get(),                 new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_MAGIC_BARS             = BOP_ITEMS.register("horizontal_magic_bars",              () -> new BlockItem(ABBlocksBOP.HORIZONTAL_MAGIC_BARS.get(),                new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_UMBRAN_BARS            = BOP_ITEMS.register("horizontal_umbran_bars",             () -> new BlockItem(ABBlocksBOP.HORIZONTAL_UMBRAN_BARS.get(),               new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_HELLBARK_BARS          = BOP_ITEMS.register("horizontal_hellbark_bars",           () -> new BlockItem(ABBlocksBOP.HORIZONTAL_HELLBARK_BARS.get(),             new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));

	public static final RegistryObject<Item> HORIZONTAL_CROSSED_FIR_BARS       = BOP_ITEMS.register("horizontal_crossed_fir_bars",        () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_FIR_BARS.get(),          new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_REDWOOD_BARS   = BOP_ITEMS.register("horizontal_crossed_redwood_bars",    () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_REDWOOD_BARS.get(),      new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_CHERRY_BARS    = BOP_ITEMS.register("horizontal_crossed_cherry_bars",     () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_CHERRY_BARS.get(),       new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_MAHOGANY_BARS  = BOP_ITEMS.register("horizontal_crossed_mahogany_bars",   () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_MAHOGANY_BARS.get(),     new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_JACARANDA_BARS = BOP_ITEMS.register("horizontal_crossed_jacaranda_bars",  () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_JACARANDA_BARS.get(),    new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_PALM_BARS      = BOP_ITEMS.register("horizontal_crossed_palm_bars",       () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_PALM_BARS.get(),         new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_WILLOW_BARS    = BOP_ITEMS.register("horizontal_crossed_willow_bars",     () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_WILLOW_BARS.get(),       new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_DEAD_BARS      = BOP_ITEMS.register("horizontal_crossed_dead_bars",       () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_DEAD_BARS.get(),         new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_MAGIC_BARS     = BOP_ITEMS.register("horizontal_crossed_magic_bars",      () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_MAGIC_BARS.get(),        new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_UMBRAN_BARS    = BOP_ITEMS.register("horizontal_crossed_umbran_bars",     () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_UMBRAN_BARS.get(),       new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));
	public static final RegistryObject<Item> HORIZONTAL_CROSSED_HELLBARK_BARS  = BOP_ITEMS.register("horizontal_crossed_hellbark_bars",   () -> new BlockItem(ABBlocksBOP.HORIZONTAL_CROSSED_HELLBARK_BARS.get(),     new Item.Properties().group(AdditionalBars.HORIZONTAL_ADDITIONAL_BARS)));

}
