package com.codenamerevy.additionalbars.common.registry;

import com.codenamerevy.additionalbars.common.AdditionalBars;
import com.codenamerevy.additionalbars.common.content.block.BlockBarsBase;
import com.codenamerevy.additionalbars.common.content.block.HorizontalBarsSlabBlock;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ABBlocks
{
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, AdditionalBars.MODID);
    public static final DeferredRegister<Block> BOP_BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, AdditionalBars.MODID);
    public static final DeferredRegister<Block> BYG_BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, AdditionalBars.MODID);

    public static final RegistryObject<Block> TEST = BLOCKS.register("test", () -> new BlockBarsBase(Block.Properties.create(Material.WOOD)));

    public static final RegistryObject<Block> GOLD_BARS                         = BLOCKS.register("gold_bars",                          () -> new BlockBarsBase(Block.Properties.create(Material.IRON, MaterialColor.GOLD).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> ACACIA_BARS                       = BLOCKS.register("acacia_bars",                        () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> BIRCH_BARS                        = BLOCKS.register("birch_bars",                         () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> JUNGLE_BARS                       = BLOCKS.register("jungle_bars",                        () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> OAK_BARS                          = BLOCKS.register("oak_bars",                           () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> DARK_OAK_BARS                     = BLOCKS.register("dark_oak_bars",                      () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> SPRUCE_BARS                       = BLOCKS.register("spruce_bars",                        () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CRIMSON_BARS                      = BLOCKS.register("crimson_bars",                       () -> new BlockBarsBase(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.CRIMSON_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));
    public static final RegistryObject<Block> WARPED_BARS                       = BLOCKS.register("warped_bars",                        () -> new BlockBarsBase(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.WARPED_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));

    public static final RegistryObject<Block> CROSSED_IRON_BARS                 = BLOCKS.register("crossed_iron_bars",                  () -> new BlockBarsBase(Block.Properties.create(Material.IRON, MaterialColor.IRON).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> CROSSED_GOLD_BARS                 = BLOCKS.register("crossed_gold_bars",                  () -> new BlockBarsBase(Block.Properties.create(Material.IRON, MaterialColor.GOLD).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> CROSSED_ACACIA_BARS               = BLOCKS.register("crossed_acacia_bars",                () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_BIRCH_BARS                = BLOCKS.register("crossed_birch_bars",                 () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_JUNGLE_BARS               = BLOCKS.register("crossed_jungle_bars",                () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_OAK_BARS                  = BLOCKS.register("crossed_oak_bars",                   () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_DARK_OAK_BARS             = BLOCKS.register("crossed_dark_oak_bars",              () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_SPRUCE_BARS               = BLOCKS.register("crossed_spruce_bars",                () -> new BlockBarsBase(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> CROSSED_CRIMSON_BARS              = BLOCKS.register("crossed_crimson_bars",               () -> new BlockBarsBase(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.CRIMSON_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));
    public static final RegistryObject<Block> CROSSED_WARPED_BARS               = BLOCKS.register("crossed_warped_bars",                () -> new BlockBarsBase(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.WARPED_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));

    public static final RegistryObject<Block> HORIZONTAL_IRON_BARS              = BLOCKS.register("horizontal_iron_bars",               () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.IRON, MaterialColor.IRON).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> HORIZONTAL_GOLD_BARS              = BLOCKS.register("horizontal_gold_bars",               () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.IRON, MaterialColor.GOLD).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> HORIZONTAL_ACACIA_BARS            = BLOCKS.register("horizontal_acacia_bars",             () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_BIRCH_BARS             = BLOCKS.register("horizontal_birch_bars",              () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_JUNGLE_BARS            = BLOCKS.register("horizontal_jungle_bars",             () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_OAK_BARS               = BLOCKS.register("horizontal_oak_bars",                () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_DARK_OAK_BARS          = BLOCKS.register("horizontal_dark_oak_bars",           () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_SPRUCE_BARS            = BLOCKS.register("horizontal_spruce_bars",             () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CRIMSON_BARS           = BLOCKS.register("horizontal_crimson_bars",            () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.CRIMSON_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));
    public static final RegistryObject<Block> HORIZONTAL_WARPED_BARS            = BLOCKS.register("horizontal_warped_bars",             () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.WARPED_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));

    public static final RegistryObject<Block> HORIZONTAL_CROSSED_IRON_BARS      = BLOCKS.register("horizontal_crossed_iron_bars",       () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.IRON, MaterialColor.IRON).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_GOLD_BARS      = BLOCKS.register("horizontal_crossed_gold_bars",       () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.IRON, MaterialColor.GOLD).sound(SoundType.METAL).harvestTool(ToolType.PICKAXE).harvestLevel(0).hardnessAndResistance(5.0F, 6.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_ACACIA_BARS    = BLOCKS.register("horizontal_crossed_acacia_bars",     () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_BIRCH_BARS     = BLOCKS.register("horizontal_crossed_birch_bars",      () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_JUNGLE_BARS    = BLOCKS.register("horizontal_crossed_jungle_bars",     () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_OAK_BARS       = BLOCKS.register("horizontal_crossed_oak_bars",        () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_DARK_OAK_BARS  = BLOCKS.register("horizontal_crossed_dark_oak_bars",   () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_SPRUCE_BARS    = BLOCKS.register("horizontal_crossed_spruce_bars",     () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(3.0F, 4.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_CRIMSON_BARS   = BLOCKS.register("horizontal_crossed_crimson_bars",    () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.CRIMSON_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));
    public static final RegistryObject<Block> HORIZONTAL_CROSSED_WARPED_BARS    = BLOCKS.register("horizontal_crossed_warped_bars",     () -> new HorizontalBarsSlabBlock(Block.Properties.create(Material.NETHER_WOOD, MaterialColor.WARPED_NYLIUM).sound(SoundType.WOOD).harvestTool(ToolType.AXE).harvestLevel(0).hardnessAndResistance(4.0F, 5.0F)));

    //TODO: Separate to an addon
    //BOP Blocks
    }

